### ISSUE TITLE
How to use it ? 

### ISSUE THREAD

**Issue by pikooli** [carlosbar/AndroidColorPicker#1]
hello , i try to use your code for a school project , but i can't see the circle picker , i put a button option with a onclick and call your object inside ,that i pass to a linearLayout ( it the main linearLayout , the one that have everything inside). 
but nothing show up when i click on option :/ 
i am using it right ? 

    public void Option(View v){
        LinearLayout colorArea = findViewById(R.id.main);
        int color= 0;
        ColorPicker colorPicker = new ColorPicker(this, color);
        colorPicker.setOnClickListener(new ColorPicker.OnClickListener() {
            @Override
            public void onColorSelected(int color) {
                print("" + color);
            }
        });
        colorArea.addView(colorPicker);
    }

**Comment by carlosbar** [comment]
Does your LinearLayout have a background color? If you don't put a
background color on it, this remains transparent.

Carlos Barcellos

Em qui, 4 de jun de 2020 08:59, pikooli <notifications@github.com> escreveu:

**Comment by pikooli** [comment]
oh yeah i didn't set a background color at first :D 
thanks

**Comment by carlosbar** [comment]
Your welcome!

Carlos Barcellos

Em qui, 4 de jun de 2020 11:14, pikooli <notifications@github.com> escreveu:

**Comment by carlosbar** [comment]
LinearLayout must have a background color
